const teams = [
    {
        team: "Anaheim Ducks",
        teamStyle: "ANA",
        facebook: "https://www.facebook.com/anaheimducks",
        instagram: "https://www.instagram.com/anaheimducks",
        tiktok: "https://www.tiktok.com/@anaheimducks",
        youtube: "https://www.youtube.com/c/AnaheimDucksOfficial",
        twitter:"https://twitter.com/AnaheimDucks",
        player1:`Teemu Selanne`,
        years1:`1995-2001, 2005-2015`,
        player2:`Paul Kariya`,
        years2:`1994-2003`,
        player3:`Scott Niedermayer`,
        years3:`2005-2010`,
        player4:`Steve Rucchin`,
        years4:`1994-2007`,
        player5:`Jean-Sebastien Giguere`,
        years5:`2000-2004, 2005-2010`,
        player6:`Guy Hebert`,
        years6:`1993-2001`,
        player7:`Corey Perry`,
        years7:`2005-2019`,
        player8:`Ryan Getzlaf`,
        years8:`2005-2022`,
        player9:`Chris Pronger`,
        years9:`2006-2009`,
        player10:`Rob Niedermayer`,
        years10:`2002-2009`,
        player11:`Ruslan Salei`,
        years11:`1996-2004, 2005-2006`
      },
      {
        team: "Arizona Coyotes",
        teamStyle: "ARI",
        facebook: "https://www.facebook.com/ArizonaCoyotes",
        instagram: "https://www.instagram.com/arizonacoyotes",
        tiktok: "https://www.tiktok.com/@nhlcoyotes",
        youtube: "https://www.youtube.com/c/ArizonaCoyotes",
        twitter:"https://twitter.com/ArizonaCoyotes",
        player1:`Shane Doan`,
        years1:`1995-2017`,
        player2:`Keith Tkachuk`,
        years2:`1996-2001`,
        player3:`Jeremy Roenick`,
        years3:`1996-2001`,
        player4:`Oliver Ekman-Larsson`,
        years4:`2010-2021`,
        player5:`Nikolai Khabibulin`,
        years5:`1996-1999`,
        player6:`Teppo Numminen`,
        years6:`1995-2003`,
        player7:`Keith Yandle`,
        years7:`2006-2015`,
        player8:`Radim Vrbata`,
        years8:`2007-2008, 2009-2014, 2016-2017`,
        player9:`Clayton Keller`,
        years9:`2016-current`,
        player10:`Curtis Joseph`,
        years10:`2005-2007`,
        player11:`Mike Smith`,
        years11:`2011-2017`
      },
      {
        team: "Boston Bruins",
        teamStyle: "BOS",
        facebook: "https://www.facebook.com/NHLBruins",
        instagram: "https://www.instagram.com/nhlbruins",
        tiktok: "https://www.tiktok.com/@nhlbruins",
        youtube: "https://www.youtube.com/user/TheNHLBruins",
        twitter:"https://twitter.com/NHLBruins",
        player1:`Bobby Orr`,
        years1:``,
        player2:`Ray Bourque`,
        years2:``,
        player3:`Phil Esposito`,
        years3:``,
        player4:`Patrice Bergeron`,
        years4:``,
        player5:`Johnny Bucyk`,
        years5:``,
        player6:`Cam Neely`,
        years6:``,
        player7:`Eddie Shore`,
        years7:``,
        player8:`Milt Schmidt`,
        years8:``,
        player9:`Brad Marchand`,
        years9:``,
        player10:`Tuukka Rask`,
        years10:``,
        player11:`Zdeno Chara`,
        years11:``
      },
    {
        team: "Buffalo Sabres",
        teamStyle: "BUF",
        facebook: "https://www.facebook.com/BuffaloSabres",
        instagram: "https://www.instagram.com/buffalosabres",
        tiktok: "https://www.tiktok.com/@buffalosabres",
        youtube: "https://www.youtube.com/user/SabresSocialMedia",
        twitter:"https://twitter.com/BuffaloSabres",
        player1:`Gilbert Perreault`,
        years1:``,
        player2:`Dominik Hasek`,
        years2:``,
        player3:`Rick Martin`,
        years3:``,
        player4:`Phil Housley`,
        years4:``,
        player5:`Pat Lafontaine`,
        years5:``,
        player6:`Alexander Mogilny`,
        years6:``,
        player7:`Dave Andreychuk`,
        years7:``,
        player8:`Ryan Miller`,
        years8:``,
        player9:`Thomas Vanek`,
        years9:``,
        player10:`Danny Gare`,
        years10:``,
        player11:`Rene Robert`,
        years11:``
      },
      {
        team: "Calgary Flames",
        teamStyle: "CGY",
        facebook: "https://www.facebook.com/NHLFlames",
        instagram: "https://www.instagram.com/nhlflames",
        tiktok: "https://www.tiktok.com/@nhlflames",
        youtube: "https://www.youtube.com/channel/UCFQqBMe3HSg6ltl09MlLHcQ",
        twitter:"https://twitter.com/NHLFlames",
        player1:`Jarome Iginla`,
        years1:``,
        player2:`Al MacInnis`,
        years2:``,
        player3:`Lanny McDonald`,
        years3:``,
        player4:`Theoren Fleury`,
        years4:``,
        player5:`Joe Nieuwendyk`,
        years5:``,
        player6:`Miikka Kiprusoff`,
        years6:``,
        player7:`Joe Mullen`,
        years7:``,
        player8:`Mike Vernon`,
        years8:``,
        player9:`Doug Gilmour`,
        years9:``,
        player10:`Mark Giordano`,
        years10:``,
        player11:`Gary Roberts`,
        years11:``
      },
      {
        team: "Carolina Hurricanes",
        teamStyle: "CAR",
        facebook: "https://www.facebook.com/Hurricanes",
        instagram: "https://www.instagram.com/canes/",
        tiktok: "https://www.tiktok.com/@canes",
        youtube: "",
        twitter:"https://twitter.com/Canes",
        player1:`Ron Francis`,
        years1:`1998-2004`,
        player2:`Eric Staal`,
        years2:`2003-2016`,
        player3:`Rod Brind'Amour`,
        years3:`1999-2010`,
        player4:`Jordan Staal`,
        years4:`2012-current`,
        player5:`Glen Wesley`,
        years5:`1997-2008`,
        player6:`Cam Ward`,
        years6:`2005-2019`,
        player7:`Sebastian Aho`,
        years7:`2016-current`,
        player8:`Erik Cole`,
        years8:`2001-2011`,
        player9:`Kevin Dineen`,
        years9:`1997-1999`,
        player10:`Justin Williams`,
        years10:`2003-2009, 2017-2020`,
        player11:`Pat Verbeek`,
        years11:`1989-1995`
      },
      {
        team: "Chicago Blackhawks",
        teamStyle: "CHI",
        facebook: "https://www.facebook.com/nhlblackhawks",
        instagram: "https://www.instagram.com/NHLBlackhawks",
        tiktok: "https://www.tiktok.com/@nhlblackhawks",
        youtube: "https://www.youtube.com/blackhawks",
        twitter:"https://twitter.com/NHLBlackhawks",
        player1: `Stan Mikita`,
        years1:`1958-1980`,
        player2:`Bobby Hull`,
        years2:`1957-1972`,
        player3:`Patrick Kane`,
        years3:`2007-2023`,
        player4:`Jonathan Toews`,
        years4:`2007-2023`,
        player5:`Denis Savard`,
        years5:`1980-1993, 1994-1997`,
        player6:`Chris Chelios`,
        years6:`1990-1999`,
        player7:`Tony Esposito`,
        years7:`1969-1984`,
        player8:`Duncan Keith`,
        years8:`2005-2021`,
        player9:`Glenn Hall`,
        years9:`1957-1967`,
        player10:`Jeremy Roenick`,
        years10:`1988-1996`,
        player11:`Ed Belfour`,
        years11:`1988-1997`
      },
      {
        team: "Colorado Avalanche",
        teamStyle: "COL",
        facebook: "https://www.facebook.com/coloradoavalanche",
        instagram: "https://www.instagram.com/coloradoavalanche/",
        tiktok: "https://www.tiktok.com/@coloradoavalanche",
        youtube: "https://www.youtube.com/user/AvalancheNHL",
        twitter:"https://twitter.com/Avalanche",
        player1: `Joe Sakic`,
        years1:`1988-2009`,
        player2:`Peter Forsberg`,
        years2:`1995-2004`,
        player3:`Patrick Roy`,
        years3:`1995-2003`,
        player4:`Nathan MacKinnon`,
        years4:`2013- current`,
        player5:`Cale Makar`,
        years5:`2019- current`,
        player6:`Mikko Rantanen`,
        years6:`2015- current`,
        player7:`Milan Hejduk`,
        years7:`1997-2014`,
        player8:`Gabriel Landeskog`,
        years8:`2011- current`,
        player9:`Adam Foote`,
        years9:`1995-2004, 2007-2011`,
        player10:`Rob Blake`,
        years10:`2000-2006`,
        player11:`Ray Bourque`,
        years11:`1999-2001`
      },
      {
        team: "Columbus Blue Jackets",
        teamStyle:"CBJ",
        facebook: "https://www.facebook.com/bluejacketsnhl",
        instagram: "https://www.instagram.com/bluejacketsnhl",
        tiktok: "https://www.tiktok.com/@bluejacketsnhl",
        youtube: "https://www.youtube.com/user/BlueJacketsNHL",
        twitter:"https://twitter.com/BlueJacketsNHL",
        player1:`Sergei Bobrovsky`,
        years1:`2012-2019`,
        player2:`Rick Nash`,
        years2:`2002-2012`,
        player3:`Marc Denis`,
        years3:`2000-2006`,
        player4:`Zach Werenski`,
        years4:`2016 - current`,
        player5:`Seth Jones`,
        years5:`2015-2021`,
        player6:`David Savard`,
        years6:`2011-2021`,
        player7:`Cam Atkinson`,
        years7:`2011-2021`,
        player8:`Nick Foligno`,
        years8:`2013-2021`,
        player9:`Artemi Panarin`,
        years9:`2017-2019`,
        player10:`Boone Jenner`,
        years10:`2013-current`,
        player11:`Sergei Fedorov`,
        years11:`2005-2008`
      },
      {
        team: "Dallas Stars",
        teamStyle: "DAL",
        facebook: "https://www.facebook.com/DallasStars",
        instagram: "https://www.instagram.com/dallasstars",
        tiktok: "https://www.tiktok.com/@dallasstars",
        youtube: "https://www.youtube.com/dallasstars",
        twitter:"https://twitter.com/dallasstars",
        player1:`Mike Modano`,
        years1:``,
        player2:`Sergei Zubov`,
        years2:``,
        player3:`Ed Belfour`,
        years3:``,
        player4:`Brett Hull`,
        years4:``,
        player5:`Jamie Benn`,
        years5:``,
        player6:`Jere Lehtinen`,
        years6:``,
        player7:`Joe Nieuwendyk`,
        years7:``,
        player8:`Brenden Morrow`,
        years8:``,
        player9:`Marty Turco`,
        years9:``,
        player10:`Derian Hatcher`,
        years10:``,
        player11:`Neal Broten`,
        years11:``
      },
      {
        team: "Detroit Red Wings",
        teamStyle: "DET",
        facebook: "https://www.facebook.com/DETROITREDWINGS/",
        instagram: "https://www.instagram.com/DetroitRedWings/index/",
        tiktok: "https://www.tiktok.com/@detroitredwings",
        youtube: "https://www.youtube.com/user/OfficialRedWings",
        twitter:"https://twitter.com/DetroitRedWings",
        player1:`Gordie Howe`,
        years1:``,
        player2:`Steve Yzerman`,
        years2:``,
        player3:`Nicklas Lindstrom`,
        years3:``,
        player4:`Pavel Datsyuk`,
        years4:``,
        player5:`Sergei Fedorov`,
        years5:``,
        player6:`Terry Sawchuk`,
        years6:``,
        player7:`Ted Lindsay`,
        years7:``,
        player8:`Red Kelly`,
        years8:``,
        player9:`Alex Delvecchio`,
        years9:``,
        player10:`Henrik Zetterberg`,
        years10:``,
        player11:`Sid Abel`,
        years11:``
      },
      {
        team: "Edmonton Oilers",
        teamStyle: "EDM",
        facebook: "https://www.facebook.com/Oilers.NHL",
        instagram: "https://www.instagram.com/edmontonoilers",
        tiktok: "https://www.tiktok.com/@edmontonoilers",
        youtube: "https://www.youtube.com/user/OilersonDemand",
        twitter:"https://twitter.com/EdmontonOilers",
        player1:`Wayne Gretzky`,
        years1:``,
        player2:`Connor Mcdavid`,
        years2:``,
        player3:`Jari Kurri`,
        years3:``,
        player4:`Mark Messier`,
        years4:``,
        player5:`Paul Coffey`,
        years5:``,
        player6:`Grant Fuhr`,
        years6:``,
        player7:`Leon Draisaitl`,
        years7:``,
        player8:`Glenn Anderson`,
        years8:``,
        player9:`Ryan Smyth`,
        years9:``,
        player10:`Esa Tikkanen`,
        years10:``,
        player11:`Bill Ranford`,
        years11:``
      },
      {
        team: "Florida Panthers",
        teamStyle: "FLA",
        facebook: "https://www.facebook.com/flapanthers",
        instagram: "https://www.instagram.com/flapanthers",
        tiktok: "https://www.tiktok.com/@flapanthers",
        youtube: "https://www.youtube.com/channel/UCSSc4wVk6telelb58RrLYdg",
        twitter:"https://twitter.com/flapanthers",
        player1:`Aleksander Barkov`,
        years1:``,
        player2:`Roberto Luongo`,
        years2:``,
        player3:`Pavel Bure`,
        years3:``,
        player4:`John Vaniesbrouck`,
        years4:``,
        player5:`Jonathan Huberdeau`,
        years5:``,
        player6:`Olli Jokinen`,
        years6:``,
        player7:`Jarmir Jagr`,
        years7:``,
        player8:`Scott Mellanby`,
        years8:``,
        player9:`Aaron Ekblad`,
        years9:``,
        player10:`Jay Bouwmeester`,
        years10:``,
        player11:`Rob Niedermayer`,
        years11:``
      },
      {
        team: "Los Angeles Kings",
        teamStyle: "LAK",
        facebook: "https://web.facebook.com/LAKings",
        instagram: "https://www.instagram.com/lakings",
        tiktok: "https://www.tiktok.com/@lakings",
        youtube: "https://www.youtube.com/LAKings",
        twitter:"https://twitter.com/LAKings",
        player1:`Marcel Dionne`,
        years1:``,
        player2:`Wayne Gretzky`,
        years2:``,
        player3:`Luc Robitaille`,
        years3:``,
        player4:`Anze Kopitar`,
        years4:``,
        player5:`Drew Doughty`,
        years5:``,
        player6:`Jonathan Quick`,
        years6:``,
        player7:`Dave Taylor`,
        years7:``,
        player8:`Rob Blake`,
        years8:``,
        player9:`Rogie Vachon`,
        years9:``,
        player10:`Bernie Nicholls`,
        years10:``,
        player11:`Charlie Simmer`,
        years11:``
      },
      {
        team: "Minnesota Wild",
        teamStyle: "MIN",
        facebook: "https://www.facebook.com/minnesotawild",
        instagram: "https://www.instagram.com/minnesotawild",
        tiktok: "https://www.tiktok.com/@mnwild",
        youtube: "https://www.youtube.com/channel/UCQRr7SxnnndFYuuRUtOIEnA/featured",
        twitter:"https://twitter.com/mnwild",
        player1:`Marian Gaborik`,
        years1:``,
        player2:`Mikko Koivu`,
        years2:``,
        player3:`Zach Parise`,
        years3:``,
        player4:`Niklas Backstrom`,
        years4:``,
        player5:`Ryan Suter`,
        years5:``,
        player6:`Devan Dubnyk`,
        years6:``,
        player7:`Jared Spurgeon`,
        years7:``,
        player8:`Mikael Granlund`,
        years8:``,
        player9:`Jonas Brodin`,
        years9:``,
        player10:`Eric Staal`,
        years10:``,
        player11:`Jason Zucker`,
        years11:``
      },
      {
        team: "Montreal Canadiens",
        teamStyle: "MTL",
        facebook: "https://www.facebook.com/canadiensmtl",
        instagram: "https://www.instagram.com/canadiensmtl",
        tiktok: "https://www.tiktok.com/@canadiensmtl",
        youtube: "https://www.youtube.com/@canadiensmtl/featured",
        twitter:"https://twitter.com/CanadiensMTL",
        player1:`Maurice Richard`,
        years1:``,
        player2:`Jean Beliveau`,
        years2:``,
        player3:`Guy Lafleur`,
        years3:``,
        player4:`Patrick Roy`,
        years4:``,
        player5:`Larry Robinson`,
        years5:``,
        player6:`Ken Dryden`,
        years6:``,
        player7:`Yvan Cournoyer`,
        years7:``,
        player8:`Jacques Plante`,
        years8:``,
        player9:`Henri Richard`,
        years9:``,
        player10:`Doug Harvey`,
        years10:``,
        player11:`Serge Savard`,
        years11:``
      },
      {
        team: "Nashville Predators",
        teamStyle: "NSH",
        facebook: "https://www.facebook.com/nashvillepredators/",
        instagram: "https://www.instagram.com/predsnhl",
        tiktok: "https://www.tiktok.com/@predsnhl",
        youtube: "https://www.youtube.com/c/nashvillepredatorsnhl",
        twitter:"https://twitter.com/predsnhl",
        player1:`Pekka Rinne`,
        years1:``,
        player2:`Roman Josi`,
        years2:``,
        player3:`Filip Forsberg`,
        years3:``,
        player4:`Sea Weber`,
        years4:``,
        player5:`Mike Fisher`,
        years5:``,
        player6:`Paul Kariya`,
        years6:``,
        player7:`David Legwand`,
        years7:``,
        player8:`Kimmo Timonen`,
        years8:``,
        player9:`Tomas Vokoun`,
        years9:``,
        player10:`Mattias Ekholm`,
        years10:``,
        player11:`Viktor Arvidsson`,
        years11:``
      },
      {
        team: "New Jersey Devils",
        teamStyle: "NJD",
        facebook: "https://www.facebook.com/NJDevils/",
        instagram: "https://www.instagram.com/njdevils/",
        tiktok: "https://www.tiktok.com/@njdevils",
        youtube: "https://www.youtube.com/@njdevils",
        twitter:"https://twitter.com/njdevils",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "New York Islanders",
        teamStyle: "NYI",
        facebook: "https://www.facebook.com/NEWYORKISLANDERS/",
        instagram: "https://www.instagram.com/ny_islanders/index/",
        tiktok: "https://www.tiktok.com/@nyislanders?lang=en",
        youtube: "https://www.youtube.com/@islanderstv",
        twitter:"https://twitter.com/NYIslanders",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "New York Rangers",
        teamStyle: "NYR",
        facebook: "https://www.facebook.com/nyrangers",
        instagram: "https://www.instagram.com/nyrangers/?hl=en",
        tiktok: "https://www.tiktok.com/@nyrangersofficial",
        youtube: "https://www.youtube.com/@nyrangers/featured",
        twitter:"https://twitter.com/NYRangers",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Ottawa Senators",
        teamStyle: "OTT",
        facebook: "https://www.facebook.com/ottawasenators",
        instagram: "https://www.instagram.com/senators/",
        tiktok: "https://www.tiktok.com/@ottawa.senators",
        youtube: "https://www.youtube.com/@OttawaSenatorsNHL",
        twitter:"https://twitter.com/Senators",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Philadelphia Flyers",
        teamStyle: "PHI",
        facebook: "https://www.facebook.com/philadelphiaflyers",
        instagram: "https://www.instagram.com/philadelphiaflyers/",
        tiktok: "https://www.tiktok.com/@nhlflyers?lang=en",
        youtube: "https://www.youtube.com/@PhiladelphiaFlyers",
        twitter:"https://twitter.com/NHLFlyers?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Pittsburgh Penguins",
        teamStyle: "PIT",
        facebook: "https://www.facebook.com/penguins",
        instagram: "https://www.instagram.com/penguins/",
        tiktok: "https://www.tiktok.com/@penguins",
        youtube: "https://www.youtube.com/penguins",
        twitter:"https://twitter.com/penguins",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "San Jose Sharks",
        teamStyle: "SJS",
        facebook: "https://www.facebook.com/SanJoseSharks/",
        instagram: "https://www.instagram.com/SanJoseSharks/index/",
        tiktok: "https://www.tiktok.com/@sanjosesharks",
        youtube: "https://www.youtube.com/sanjosesharks",
        twitter:"https://twitter.com/SanJoseSharks",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Seattle Kraken",
        teamStyle: "SEA",
        facebook: "https://www.facebook.com/seattlekraken",
        instagram: "https://www.instagram.com/seattlekraken/",
        tiktok: "https://www.tiktok.com/@seattlekraken",
        youtube: "https://www.youtube.com/SeattleKraken",
        twitter:"https://twitter.com/SeattleKraken",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Tampa Bay Lightning",
        teamStyle: "TBL",
        facebook: "https://www.facebook.com/lightningnhl/",
        instagram: "https://www.instagram.com/tblightning/index/",
        tiktok: "https://www.tiktok.com/@tblightning?lang=en",
        youtube: "https://www.youtube.com/channel/UCgC7zVCS9UJg-ziFINnwzyA",
        twitter:"https://twitter.com/TBLightning",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Vancouver Canucks",
        teamStyle: "VAN",
        facebook: "https://www.facebook.com/Canucks",
        instagram: "https://www.instagram.com/canucks/",
        tiktok: "https://www.tiktok.com/@canucks",
        youtube: "https://www.youtube.com/canucks",
        twitter:"https://twitter.com/Canucks",
        player1:`Henrik Sedin`,
        years1:``,
        player2:`Pavel Bure`,
        years2:``,
        player3:`Daniel Sedin`,
        years3:``,
        player4:`Trevor Linden`,
        years4:``,
        player5:`Markus Naslund`,
        years5:``,
        player6:`Robert Luongo`,
        years6:``,
        player7:`Kirk McLean`,
        years7:``,
        player8:`Elias Pettersson`,
        years8:``,
        player9:`Stan Smyl`,
        years9:``,
        player10:`Kevin Bieksa`,
        years10:``,
        player11:`Bo Horvat`,
        years11:``
      },
      {
        team: "Vegas Golden Knights",
        teamStyle: "VGK",
        facebook: "https://www.facebook.com/vegasgoldenknights",
        instagram: "https://www.instagram.com/vegasgoldenknights/?hl=en",
        tiktok: "https://www.tiktok.com/@vegasgoldenknights",
        youtube: "https://www.youtube.com/channel/UCyUzGmp1kAmlkNUzAqW9xJw",
        twitter:"https://twitter.com/GoldenKnights",
        player1:`Shea Theodore`,
        years1:``,
        player2:`Jonathan Marchessault`,
        years2:``,
        player3:`William Karlson`,
        years3:``,
        player4:`Marc-Andre Fleury`,
        years4:``,
        player5:`Reilly Smith`,
        years5:``,
        player6:`Mark Stone`,
        years6:``,
        player7:`Brayden McNabb`,
        years7:``,
        player8:`Max Pacioretty`,
        years8:``,
        player9:`Alex Petrangelo`,
        years9:``,
        player10:`Jack Eichel`,
        years10:``,
        player11:`Chandler Stephenson`,
        years11:``
      },
      {
        team: "Washington Capitals",
        teamStyle: "WSH",
        facebook: "https://www.facebook.com/Capitals",
        instagram: "https://www.instagram.com/capitals/",
        tiktok: "https://www.tiktok.com/@capitals",
        youtube: "https://www.youtube.com/capitals",
        twitter:"https://twitter.com/capitals",
        player1:`Alexander Ovechkin`,
        years1:``,
        player2:`Nicklas Backstrom`,
        years2:``,
        player3:`Peter Bondra`,
        years3:``,
        player4:`Rod Langway`,
        years4:``,
        player5:`T.J. Oshie`,
        years5:``,
        player6:`Mike Gartner`,
        years6:``,
        player7:`Olaf Kolzig`,
        years7:``,
        player8:`John Carlson`,
        years8:``,
        player9:`Dale Hunter`,
        years9:``,
        player10:`Braden Holtby`,
        years10:``,
        player11:`Dino Ciccarelli`,
        years11:``
      },
      {
        team: "Winnipeg Jets",
        teamStyle: "WPG",
        facebook: "https://www.facebook.com/nhljets",
        instagram: "https://www.instagram.com/NHLJets/",
        tiktok: "https://www.tiktok.com/@nhljets",
        youtube: "https://www.youtube.com/NHLJets",
        twitter:"https://twitter.com/NHLJets",
        player1:`Dale Hawerchuk`,
        years1:``,
        player2:`Teemu Selanne`,
        years2:``,
        player3:`Bobby Hull`,
        years3:``,
        player4:`Anders Hedberg`,
        years4:``,
        player5:`Phil Housley`,
        years5:``,
        player6:`Teppo Numminen`,
        years6:``,
        player7:`Thomas Steen`,
        years7:``,
        player8:`Ulf Nilsson`,
        years8:``,
        player9:`Blake Wheeler`,
        years9:``,
        player10:`Keith Tkachuk`,
        years10:``,
        player11:`Dustin Byfuglien`,
        years11:``
      },
];

export default teams;