const teams = [
    {
        team: "Anaheim Ducks",
        teamStyle: "ANA",
        facebook: "https://www.facebook.com/anaheimducks",
        instagram: "https://www.instagram.com/anaheimducks",
        tiktok: "https://www.tiktok.com/@anaheimducks",
        youtube: "https://www.youtube.com/c/AnaheimDucksOfficial",
        twitter:"https://twitter.com/AnaheimDucks",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Arizona Coyotes",
        teamStyle: "ARI",
        facebook: "https://www.facebook.com/ArizonaCoyotes",
        instagram: "https://www.instagram.com/arizonacoyotes",
        tiktok: "https://www.tiktok.com/@nhlcoyotes",
        youtube: "https://www.youtube.com/c/ArizonaCoyotes",
        twitter:"https://twitter.com/ArizonaCoyotes",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Boston Bruins",
        teamStyle: "BOS",
        facebook: "https://www.facebook.com/NHLBruins",
        instagram: "https://www.instagram.com/nhlbruins",
        tiktok: "https://www.tiktok.com/@nhlbruins",
        youtube: "https://www.youtube.com/user/TheNHLBruins",
        twitter:"https://twitter.com/NHLBruins",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
    {
        team: "Buffalo Sabres",
        teamStyle: "BUF",
        facebook: "https://www.facebook.com/BuffaloSabres",
        instagram: "https://www.instagram.com/buffalosabres",
        tiktok: "https://www.tiktok.com/@buffalosabres",
        youtube: "https://www.youtube.com/user/SabresSocialMedia",
        twitter:"https://twitter.com/BuffaloSabres",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Calgary Flames",
        teamStyle: "CGY",
        facebook: "https://www.facebook.com/NHLFlames",
        instagram: "https://www.instagram.com/nhlflames",
        tiktok: "https://www.tiktok.com/@nhlflames",
        youtube: "https://www.youtube.com/channel/UCFQqBMe3HSg6ltl09MlLHcQ",
        twitter:"https://twitter.com/NHLFlames",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Carolina Hurricanes",
        teamStyle: "CAR",
        facebook: "https://www.facebook.com/Hurricanes",
        instagram: "https://www.instagram.com/canes/",
        tiktok: "https://www.tiktok.com/@canes",
        youtube: "",
        twitter:"https://twitter.com/Canes",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Chicago Blackhawks",
        teamStyle: "CHI",
        facebook: "https://www.facebook.com/nhlblackhawks",
        instagram: "https://www.instagram.com/NHLBlackhawks",
        tiktok: "https://www.tiktok.com/@nhlblackhawks",
        youtube: "https://www.youtube.com/blackhawks",
        twitter:"https://twitter.com/NHLBlackhawks",
        player1: `Stan Mikita`,
        years1:`1958-1980`,
        player2:`Bobby Hull`,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Colorado Avalanche",
        teamStyle: "COL",
        facebook: "https://www.facebook.com/coloradoavalanche",
        instagram: "https://www.instagram.com/coloradoavalanche/",
        tiktok: "https://www.tiktok.com/@coloradoavalanche",
        youtube: "https://www.youtube.com/user/AvalancheNHL",
        twitter:"https://twitter.com/Avalanche",
        player1: `Joe Sakic`,
        years1:`1988-2009`,
        player2:`Peter Forsberg`,
        years2:`1995-2004`,
        player3:`Patrick Roy`,
        years3:`1995-2003`,
        player4:`Nathan MacKinnon`,
        years4:`2013 - current`,
        player5:`Cale Makar`,
        years5:`2019 - current`,
        player6:`Mikko Rantanen`,
        years6:`2015 - current`,
        player7:`Milan Hejduk`,
        years7:`1997-2014`,
        player8:`Gabriel Landeskog`,
        years8:`2011- current`,
        player9:`Adam Foote`,
        years9:`1995-2004, 2007-2011`,
        player10:`Rob Blake`,
        years10:`2000-2006`,
        player11:`Ray Bourque`,
        years11:`1999-2001`
      },
      {
        team: "Columbus Blue Jackets",
        teamStyle:"CBJ",
        facebook: "https://www.facebook.com/bluejacketsnhl",
        instagram: "https://www.instagram.com/bluejacketsnhl",
        tiktok: "https://www.tiktok.com/@bluejacketsnhl",
        youtube: "https://www.youtube.com/user/BlueJacketsNHL",
        twitter:"https://twitter.com/BlueJacketsNHL",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Dallas Stars",
        teamStyle: "DAL",
        facebook: "https://www.facebook.com/DallasStars",
        instagram: "https://www.instagram.com/dallasstars",
        tiktok: "https://www.tiktok.com/@dallasstars",
        youtube: "https://www.youtube.com/dallasstars",
        twitter:"https://twitter.com/dallasstars",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Detroit Red Wings",
        teamStyle: "DET",
        facebook: "https://www.facebook.com/DETROITREDWINGS/",
        instagram: "https://www.instagram.com/DetroitRedWings/index/",
        tiktok: "https://www.tiktok.com/@detroitredwings",
        youtube: "https://www.youtube.com/user/OfficialRedWings",
        twitter:"https://twitter.com/DetroitRedWings",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Edmonton Oilers",
        teamStyle: "EDM",
        facebook: "https://www.facebook.com/Oilers.NHL",
        instagram: "https://www.instagram.com/edmontonoilers",
        tiktok: "https://www.tiktok.com/@edmontonoilers",
        youtube: "https://www.youtube.com/user/OilersonDemand",
        twitter:"https://twitter.com/EdmontonOilers",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Florida Panthers",
        teamStyle: "FLA",
        facebook: "https://www.facebook.com/flapanthers",
        instagram: "https://www.instagram.com/flapanthers",
        tiktok: "https://www.tiktok.com/@flapanthers",
        youtube: "https://www.youtube.com/channel/UCSSc4wVk6telelb58RrLYdg",
        twitter:"https://twitter.com/flapanthers",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Los Angeles Kings",
        teamStyle: "LAK",
        facebook: "https://web.facebook.com/LAKings",
        instagram: "https://www.instagram.com/lakings",
        tiktok: "https://www.tiktok.com/@lakings",
        youtube: "https://www.youtube.com/LAKings",
        twitter:"https://twitter.com/LAKings",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Minnesota Wild",
        teamStyle: "MIN",
        facebook: "https://www.facebook.com/minnesotawild",
        instagram: "https://www.instagram.com/minnesotawild",
        tiktok: "https://www.tiktok.com/@mnwild",
        youtube: "https://www.youtube.com/channel/UCQRr7SxnnndFYuuRUtOIEnA/featured",
        twitter:"https://twitter.com/mnwild",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Montreal Canadiens",
        teamStyle: "MTL",
        facebook: "https://www.facebook.com/canadiensmtl",
        instagram: "https://www.instagram.com/canadiensmtl",
        tiktok: "https://www.tiktok.com/@canadiensmtl",
        youtube: "https://www.youtube.com/@canadiensmtl/featured",
        twitter:"https://twitter.com/CanadiensMTL",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Nashville Predators",
        teamStyle: "NSH",
        facebook: "https://www.facebook.com/nashvillepredators/",
        instagram: "https://www.instagram.com/predsnhl",
        tiktok: "https://www.tiktok.com/@predsnhl",
        youtube: "https://www.youtube.com/c/nashvillepredatorsnhl",
        twitter:"https://twitter.com/predsnhl",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "New Jersey Devils",
        teamStyle: "NJD",
        facebook: "https://www.facebook.com/NJDevils/",
        instagram: "https://www.instagram.com/njdevils/",
        tiktok: "https://www.tiktok.com/@njdevils",
        youtube: "https://www.youtube.com/@njdevils",
        twitter:"https://twitter.com/njdevils",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "New York Islanders",
        teamStyle: "NYI",
        facebook: "https://www.facebook.com/NEWYORKISLANDERS/",
        instagram: "https://www.instagram.com/ny_islanders/index/",
        tiktok: "https://www.tiktok.com/@nyislanders?lang=en",
        youtube: "https://www.youtube.com/@islanderstv",
        twitter:"https://twitter.com/NYIslanders",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "New York Rangers",
        teamStyle: "NYR",
        facebook: "https://www.facebook.com/nyrangers",
        instagram: "https://www.instagram.com/nyrangers/?hl=en",
        tiktok: "https://www.tiktok.com/@nyrangersofficial",
        youtube: "https://www.youtube.com/@nyrangers/featured",
        twitter:"https://twitter.com/NYRangers",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Ottawa Senators",
        teamStyle: "OTT",
        facebook: "https://www.facebook.com/ottawasenators",
        instagram: "https://www.instagram.com/senators/",
        tiktok: "https://www.tiktok.com/@ottawa.senators",
        youtube: "https://www.youtube.com/@OttawaSenatorsNHL",
        twitter:"https://twitter.com/Senators",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Philadelphia Flyers",
        teamStyle: "PHI",
        facebook: "https://www.facebook.com/philadelphiaflyers",
        instagram: "https://www.instagram.com/philadelphiaflyers/",
        tiktok: "https://www.tiktok.com/@nhlflyers?lang=en",
        youtube: "https://www.youtube.com/@PhiladelphiaFlyers",
        twitter:"https://twitter.com/NHLFlyers?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Pittsburgh Penguins",
        teamStyle: "PIT",
        facebook: "https://www.facebook.com/penguins",
        instagram: "https://www.instagram.com/penguins/",
        tiktok: "https://www.tiktok.com/@penguins",
        youtube: "https://www.youtube.com/penguins",
        twitter:"https://twitter.com/penguins",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "San Jose Sharks",
        teamStyle: "SJS",
        facebook: "https://www.facebook.com/SanJoseSharks/",
        instagram: "https://www.instagram.com/SanJoseSharks/index/",
        tiktok: "https://www.tiktok.com/@sanjosesharks",
        youtube: "https://www.youtube.com/sanjosesharks",
        twitter:"https://twitter.com/SanJoseSharks",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Seattle Kraken",
        teamStyle: "SEA",
        facebook: "https://www.facebook.com/seattlekraken",
        instagram: "https://www.instagram.com/seattlekraken/",
        tiktok: "https://www.tiktok.com/@seattlekraken",
        youtube: "https://www.youtube.com/SeattleKraken",
        twitter:"https://twitter.com/SeattleKraken",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Tampa Bay Lightning",
        teamStyle: "TBL",
        facebook: "https://www.facebook.com/lightningnhl/",
        instagram: "https://www.instagram.com/tblightning/index/",
        tiktok: "https://www.tiktok.com/@tblightning?lang=en",
        youtube: "https://www.youtube.com/channel/UCgC7zVCS9UJg-ziFINnwzyA",
        twitter:"https://twitter.com/TBLightning",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Vancouver Canucks",
        teamStyle: "VAN",
        facebook: "https://www.facebook.com/Canucks",
        instagram: "https://www.instagram.com/canucks/",
        tiktok: "https://www.tiktok.com/@canucks",
        youtube: "https://www.youtube.com/canucks",
        twitter:"https://twitter.com/Canucks",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Vegas Golden Knights",
        teamStyle: "VGK",
        facebook: "https://www.facebook.com/vegasgoldenknights",
        instagram: "https://www.instagram.com/vegasgoldenknights/?hl=en",
        tiktok: "https://www.tiktok.com/@vegasgoldenknights",
        youtube: "https://www.youtube.com/channel/UCyUzGmp1kAmlkNUzAqW9xJw",
        twitter:"https://twitter.com/GoldenKnights",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Washington Capitals",
        teamStyle: "WSH",
        facebook: "https://www.facebook.com/Capitals",
        instagram: "https://www.instagram.com/capitals/",
        tiktok: "https://www.tiktok.com/@capitals",
        youtube: "https://www.youtube.com/capitals",
        twitter:"https://twitter.com/capitals",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
      {
        team: "Winnipeg Jets",
        teamStyle: "WPG",
        facebook: "https://www.facebook.com/nhljets",
        instagram: "https://www.instagram.com/NHLJets/",
        tiktok: "https://www.tiktok.com/@nhljets",
        youtube: "https://www.youtube.com/NHLJets",
        twitter:"https://twitter.com/NHLJets",
        player1:``,
        years1:``,
        player2:``,
        years2:``,
        player3:``,
        years3:``,
        player4:``,
        years4:``,
        player5:``,
        years5:``,
        player6:``,
        years6:``,
        player7:``,
        years7:``,
        player8:``,
        years8:``,
        player9:``,
        years9:``,
        player10:``,
        years10:``,
        player11:``,
        years11:``
      },
];

export default teams;